title: John Doe
author: Andrzej Kłapeć
email: john@johndoe.com
description: Site description
keywords: freelance, web developer, web design, development, UI designer, freelance developer, jekyll, sass, front-end developer, Joe Doe, freelance designer, freelance developer

baseurl: "/simple-personal" # Change to "" for local development
url: "http://klapec.github.io/simple-personal" # Change to your remote URL

github: klapec

markdown: redcarpet
redcarpet:
  extensions: ["smart", "autolink", "tables", "no_intra_emphasis", "strikethrough", "underline", "quote", "footnotes"]

exclude: ['assets/src', 'node_modules', 'package.json', 'gulpfile.js', 'LICENSE', 'README.md', 'simple-personal.sublime-project']

timezone: Europe/Warsaw

permalink: none
